plugins { id 'com.android.application' }

android {
    namespace 'com.syedhuzaif.udppong'
    compileSdk 36

    defaultConfig {
        applicationId 'com.syedhuzaif.udppong'
        minSdk 29
        targetSdk 36
        versionCode 130
        versionName '1.3.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            ndk { debugSymbolLevel 'SYMBOL_TABLE' }
        }
    }
}
